In [27]:
import numpy as np
import torch
import torch.distributions as td

def all_one_hot_combinations(N, K):
    # N is number of 1's in the hot vector
    return np.eye(K).take(np.reshape(np.indices([K] * N), [N, -1]).T, axis=0).reshape(-1, N * K)  # [K**N, N*K]

N = 1
K = 5

val = all_one_hot_combinations(N, K)
print(val)
z_dim = N*K

h = torch.randn(N*K)
logits_separated = torch.reshape(h, (-1, N, K))
logits_separated_mean_zero = logits_separated - torch.mean(logits_separated, dim=-1, keepdim=True)
dist = td.OneHotCategorical(logits=logits_separated_mean_zero)
dist.sample()
bs = dist.probs.size()[0]
print(bs)

num_components = N*K
num_samples = 1
z_NK = torch.from_numpy(all_one_hot_combinations(N, K)).float().repeat(num_samples, bs)
z_stacked = torch.reshape(z_NK, (num_samples * num_components, -1, N*K))
z = torch.reshape(z_stacked, (-1, z_dim))


print(dist.logits.repeat(1, 1, 1))

# k is number of samples - we just have 1 sample
# number of components is N*K???

# why are we reshaping to be [num_samples * num_components, -1, N*K]?
# because we want to sample from the distribution, and we want to sample from each component of the distribution

print(z_NK)
print(z.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
1
tensor([[[-0.8448, -1.4859, -2.6522, -2.9047, -1.5197]]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
torch.Size([5, 5])
